<a href="https://colab.research.google.com/github/Aditi840/Guvi-Tasks/blob/main/DataPreprocessing_Assignment11_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Data.csv

**Step 1: Importing the libraries**

In [20]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

**Step 2: Importing dataset**

In [11]:
df = pd.read_csv('/content/Data.csv')

In [12]:
print(df)
print(df.columns)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes
Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')


**Step 3: Handling the missing data**

In [13]:
print(df.isnull())

   Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False


In [14]:
# Replace missing values with the mean age and salary
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Salary'].fillna(df['Salary'].mean(), inplace=True)
print(df)

   Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes


**Step 4: Encoding categorical data**

In [15]:
le = LabelEncoder()
df['Purchased'] = le.fit_transform(df['Purchased'])
print(df)

   Country        Age        Salary  Purchased
0   France  44.000000  72000.000000          0
1    Spain  27.000000  48000.000000          1
2  Germany  30.000000  54000.000000          0
3    Spain  38.000000  61000.000000          0
4  Germany  40.000000  63777.777778          1
5   France  35.000000  58000.000000          1
6    Spain  38.777778  52000.000000          0
7   France  48.000000  79000.000000          1
8  Germany  50.000000  83000.000000          0
9   France  37.000000  67000.000000          1


**Step 5: Creating a dummy variable**

In [16]:
# Create dummy variables for the 'Country' column
dummy_vars = pd.get_dummies(df['Country'])
df = pd.concat([df, dummy_vars], axis=1)

# Drop the original 'Country' column
df.drop('Country', axis=1, inplace=True)

# Print the updated dataset
print(df)

         Age        Salary  Purchased  France  Germany  Spain
0  44.000000  72000.000000          0       1        0      0
1  27.000000  48000.000000          1       0        0      1
2  30.000000  54000.000000          0       0        1      0
3  38.000000  61000.000000          0       0        0      1
4  40.000000  63777.777778          1       0        1      0
5  35.000000  58000.000000          1       1        0      0
6  38.777778  52000.000000          0       0        0      1
7  48.000000  79000.000000          1       1        0      0
8  50.000000  83000.000000          0       0        1      0
9  37.000000  67000.000000          1       1        0      0


**Step 6: Splitting the datasets into training sets and Test sets**

In [19]:
# Split the dataset into features (X) and target variable (y)
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Print the shape of the training and testing sets
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X_train shape: (8, 5)
y_train shape: (8,)
X_test shape: (2, 5)
y_test shape: (2,)


**Step 7: Feature Scaling**

In [21]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Print the standardized features
print("X_train:", X_train)
print("X_test:", X_test)

X_train: [[ 0.26306757  0.12381479  0.77459667 -1.          2.64575131]
 [-0.25350148  0.46175632  0.77459667  1.         -0.37796447]
 [-1.97539832 -1.53093341  0.77459667 -1.         -0.37796447]
 [ 0.05261351 -1.11141978 -1.29099445 -1.         -0.37796447]
 [ 1.64058505  1.7202972   0.77459667  1.         -0.37796447]
 [-0.0813118  -0.16751412 -1.29099445 -1.         -0.37796447]
 [ 0.95182631  0.98614835 -1.29099445  1.         -0.37796447]
 [-0.59788085 -0.48214934  0.77459667  1.         -0.37796447]]
X_test: [[-1.45882927 -0.90166297 -1.29099445 -1.          2.64575131]
 [ 1.98496442  2.13981082 -1.29099445 -1.          2.64575131]]
